---
output: 
  rmarkdown::word_document: 
    reference_docx: "../templates/ref.docx"
bibliography: "../lit/empathy.bib"
csl: "../lit/apa.csl"
---

# The Empathy Quotient [@baron2004empathy]

#### Instructions

- Below is a list of statements. 
Please read each statement carefully and rate how strongly you agree or disagree with it by circling your answer. 
There are no right or wrong answers, or trick questions.
- In order for the scale to be valid, you must answer every question.  

#### Items

1. I can easily tell if someone else wants to enter a conversation.
2. I prefer animals to humans.
3. I try to keep up with the current trends and fashions.
4. I find it difficult to explain to others things that I understand easily, when they don’t understand it first time.
5. I dream most nights.
6. I really enjoy caring for other people.
7. I try to solve my own problems rather than discussing them with others.
8. I find it hard to know what to do in a social situation.
9. I am at my best first thing in the morning.
10. People often tell me that I went too far in driving my point home in a discussion.
11. It doesn’t bother me too much if I am late meeting a friend.
12. Friendships and relationships are just too difficult, so I tend not to bother with them.
13. I would never break a law, no matter how minor.
14. I often find it difficult to judge if something is rude or polite.
15. In a conversation, I tend to focus on my own thoughts rather than on what my listener might be thinking.
16. I prefer practical jokes to verbal humor.
17. I live life for today rather than the future.
18. When I was a child, I enjoyed cutting up worms to see what would happen.
19. I can pick up quickly if someone says one thing but means another.
20. I tend to have very strong opinions about morality.
21. It is hard for me to see why some things upset people so much.
22. I find it easy to put myself in somebody else’s shoes.
23. I think that good manners are the most important thing a parent can teach their child.
24. I like to do things on the spur of the moment.
25. I am good at predicting how someone will feel.
26. I am quick to spot when someone in a group is feeling awkward or uncomfortable.
27. If I say something that someone else is offended by, I think that that’s their problem, not mine.
28. If anyone asked me if I liked their haircut, I would reply truthfully, even if I didn’t like it.
29. I can’t always see why someone should have felt offended by a remark.
30. People often tell me that I am very unpredictable.
31. I enjoy being the center of attention at any social gathering.
32. Seeing people cry doesn’t really upset me.
33. I enjoy having discussions about politics.
34. I am very blunt, which some people take to be rudeness, even though this is unintentional.
35. I don’t tend to find social situations confusing.
36. Other people tell me I am good at understanding how they are feeling and what they are thinking.
37. When I talk to people, I tend to talk about their experiences rather than my own.
38. It upsets me to see an animal in pain.
39. I am able to make decisions without being influenced by people’s feelings.
40. I can’t relax until I have done everything I had planned to do that day.
41. I can easily tell if someone else is interested or bored with what I am saying.
42. I get upset if I see people suffering on news programmes.
43. Friends usually talk to me about their problems as they say that I am very understanding.
44. I can sense if I am intruding, even if the other person doesn’t tell me.
45. I often start new hobbies but quickly become bored with them and move on to something else.
46. People sometimes tell me that I have gone too far with teasing.
47. I would be too nervous to go on a big rollercoaster.
48. Other people, often say that I am insensitive, though I don’t always see why.
49. If I see a stranger in a group, I think that it is up to them to make an effort to join in.
50. I usually stay emotionally detached when watching a film.
51. I like to be very organized in day-to-day life and often make lists of the chores I have to do.
52. I can tune into how someone else feels rapidly and intuitively.
53. I don’t like to take risks.
54. I can easily work out what another person might want to talk about.
55. I can tell if someone is masking their true emotion.
56. Before making a decision I always weigh up the pros and cons.
57. I don’t consciously work out the rules of social situations.
58. I am good at predicting what someone will do.
59. I tend to get emotionally involved with a friend’s problems.
60. I can usually appreciate the other person’s viewpoint, even if I don’t agree with it.


# Item info

```{r, echo=F}
# Vector of all items
all_items <- 1:60

# Vector of test items
test_items <- c(1, 6, 19, 22, 25, 26, 35, 36, 37, 38, 41, 42, 43, 44, 52, 54, 
  55, 57, 58, 59, 60, 4, 8, 10, 11, 12, 14, 15, 18, 21, 27, 28, 29, 32, 34, 
  39, 46, 48, 49, 50)

# Vector of logicals indicating if test item (TRUE) or filler (FALSE)
is_test <- all_items %in% test_items

# Subset all items to get vector of filler items
filler_items <- all_items[!is_test]

# Check to see if filler items appear in test items (should all be false)
filler_test <- filler_items %in% test_items
```

#### Test items (40)

`r knitr::combine_words(sort(test_items))`

#### Filler items (20)

`r knitr::combine_words(sort(filler_items))`

#### Response options

- strongly agree
- slightly agree 
- slightly disagree
- strongly disagree

#### Scoring

- Items: 1, 6, 19, 22, 25, 26, 35, 36, 37, 38, 41, 42, 43, 44, 52, 54, 55, 57, 58, 59, 60.
	- “Definitely agree” responses scored 2 points 
	- “slightly agree” responses scored 1 point 
- Items: 4, 8, 10, 11, 12, 14, 15, 18, 21, 27, 28, 29, 32, 34, 39, 46, 48, 49, 50.
	- “Definitely disagree” responses scored 2 points
	- “slightly disagree” responses scored 1 point on the following

#### Operationalization

“Empathy is the drive or ability to attribute mental states to another person/animal, and entails an appropriate affective response in the observer to the other person’s mental state.”

# References
