# Scratch

# Introduction

What is known:  In recent research in L2 acquisition, increasing attention has been given to how individual differences in learner backgrounds play a role in the process of L2 acquisition. 
For instance, variation in cognitive processes such as working memory capacity has pointed to important differences in L2 processing and learning. Recent research has also suggested that individual differences in pragmatic skills, such as empathy, may play a role in meaning disambiguation. According to Esteve-Gibert et al., 2020, empathy can be understood as it is related to theory of mind and perspective taking (Baron-Cohen, 2011; Carruthers, 2009; Frith & Frith, 2003). In other words, those with higher empathy are expected to more effectively take the perspective of another, and past research has investigated whether better perspective taking is related to more effective meaning disambiguation. Evidence has been found for the use of intonational cues to disambiguate meaning by higher empathy individuals in monolingual speech (Esteve-Gibert et al., 2020). On the other hand, there is also evidence that higher proficiency Spanish speakers can effectively distinguish questions from statements (Brandl et al., 2020). 

What is not well known: It is unclear whether those with higher empathy also take advantage of intonational cues to infer another speaker’s communicative intent in a second language when proficiency is also taken into account.   

How we address the gap: The present study investigates whether L2 learners of Spanish with higher empathy are more effective in distinguishing statements from questions when proficiency is held constant. 


# Background and motivation

## L2 acquisition of prosody

Brandl et al. (2020) investigated the perceptual development of intonation in questions and statements in L2 Spanish. Specifically, they examined the effect of L2 proficiency on the perception of statements (broad-focus and narrow-focus) and questions (wh-questions and yes/no questions). Adult English L1-Spanish L2 learners (beginner, intermediate, and advanced) and adult native speakers of Spanish completed an AX discrimination task in which they were presented with two stimuli sentences at a time, one aural and one visual. Participants had to decide whether the sentence presented aurally was the same as the sentence presented visually by pressing a button (‘yes’, ‘no’). The aural stimuli was recorded by 8 native speakers of Spanish from different Spanish varieties. The task had match and mismatch conditions, and it measured response accuracy and response times. 

Results indicated that overall perception accuracy was modulated by Spanish proficiency. Native speakers had the highest accuracy rate, followed by intermediate learners and beginner learners. Accuracy was high in match conditions, but accuracy in mismatch conditions was below chance for all L2 learners. In addition, results showed an effect of sentence type. Overall, questions had a higher accuracy rate than statements for all groups, with wh-questions having the highest accuracy percentage. No effect of statement type (broad-focus or narrow-focus) was found. 
In terms of response times, intermediate learners were the fastest overall, and native speakers were the slowest. Sentences in the match condition yielded faster responses than sentences in the mismatch condition, but only for beginner and advanced learners. Learners with lower proficiency processed statements faster than questions. Brandl et al. (2020) concluded that L2 intonation perception differs from L1 intonation perception in Spanish, that L2 intonation perception undergoes a gradual development as L2 acquisition progresses, and that statements are more easily processed and acquired by L2 learners of Spanish, compared to yes/no questions. 

Importantly, the authors stated that the study had some limitations.
First, the nature of the task may have raised participants’ metalinguistic awareness of intonational differences since they were explicitly asked to compare the aural and visual stimuli. 
Additionally, the fact that participants were presented with two types of input (aural and visual) at the same time may have influenced their perception, considering that visual input has been shown to influence aural perception (Shook and Marian, 2013, NEED MORE REFS).
Besides, the items used in the wh-question mismatch condition contained syntactic differences apart from intonational differences (e.g., ¿Por qué iba Daniel a Bolivia? vs Daniel iba a Bolivia). In this condition, participants may have been able to identify the mismatch since the beginning of the sentence by comparing the syntactic structure and word order without the need of intonational discrimination. This flaw may have influenced participants’ perception of wh-questions, which may explain why the results showed that wh-questions had the highest accuracy rate. 
Second, the authors mentioned that it is possible that dialectal or sociolectal variation could have influenced participants’ responses. In fact, the stimuli sentences included recordings of 8 different varieties of Spanish, but dialectal variation was not included in the analysis. Whether intonation perception varies across Spanish varieties still remains unclear.  
Lastly, the study did not include an objective measure of L2 proficiency. L2 proficiency was established based on the course that English-Spanish learners were enrolled in, which may not provide an accurate representation of L2 proficiency level. In spite of this, the proficiency effects reported in the study were found as expected.

## Spanish prosody

Spanish is extensively spoken across the world, with relatively small geolectal differences between its varieties compared to other languages, so that speakers from distinct regions can still generally understand each other. This linguistic continuum allows, however, for variation to occur… 

## Empathy 

Speakers use intonational cues to express feelings, intentions, and pragmatic meaning (see Prieto, 2015), but listeners vary in how they interpret intonational cues to infer meaning (e.g., Bishop, 2016; Bishop and Kuo, 2016; Portes et al., 2014). This variability could be related to differences in individual pragmatic skills. Previous studies have shown that individual pragmatic skills correlate with variability in semantic/pragmatic interpretation of ambiguous linguistic items, with more pragmatic individuals preferring pragmatically enriched interpretations and less pragmatic individuals preferring literal/semantic interpretations (e.g., Degen and Tanenhaus, 2015; Nieuwland et al., 2010). In addition, more pragmatically skilled individuals and less pragmatically skilled individuals tend to rely on different phonetic cues to parse syntactically ambiguous sentences (Bishop, 2016). It is possible that variability in intonation processing is also linked to individual differences in pragmatic skills.
Recent studies have explored the possibility that individual pragmatic skills can modulate the sensitivity of listeners to intonational cues that convey pragmatic meaning. Esteve-Gilbert et al. (2020) focused specifically on empathy, which is a pragmatic skill that helps listeners understand other peoples’ feelings, emotions, intentions, and behavior (Baron-Cohen and Wheelwright, 2004). Esteve-Gilbert et al. (2020) investigated whether listeners’ empathy modulated variability in intonation processing. Empathy was measured using a self-reported Empathy Quotient (EQ) questionnaire (Baron-Cohen & Wheelwright, 2004). Esteve-Gilbert et al. (2020) tested French monolinguals in a visual-world paradigm eye-tracking task that resembled a card guessing game. Participants listened to short dialogues in French between two players (Player A and Player B) playing a card guessing game as they saw a display of four objects on a screen. Participants had to identify the object that depicted the picture of the card of one of the players. Target objects were homophones in French (e.g., cane - “female duck”; canne - “walking stick”). The dialogues consisted of a suggestion by Player A (e.g., “I think you have a stick”) followed by Player B’s response, which could confirm (e.g., “I have a stick, indeed, to walk”) or contrast (e.g., “I have a female duck, instead, the animal”) Player A’s suggestion. The first portion of Player B’s responses varied in intonational contours (confirmation or contrast of beliefs) and had subsequent disambiguating lexical information (indeed/instead + additional information). Results indicated that empathy level affected the processing of an ambiguous word (a homophone) when intonation was the only cue available. Highly empathic individuals varied their looking behavior as a function of intonational cues while less empathic individuals did not. However, the direction of the looking behavior of the highly empathic individuals was not as expected and reverse intonation-meaning mapping was observed. Confirmation intonation did not trigger more looks to the suggested image and contrast intonation did not trigger more looks to objects other than the suggested image. 
To explore this unexpected finding further, Esteve-Gilbert et al. (2020) tested an additional group of French monolinguals in an offline matching task in which they listened only to the ambiguous portion of Player B’s response (e.g., “I have a stick.”, “I have a female duck.”) and matched the sentences to either a confirmatory or contrastive meaning. Intonation was the only disambiguating cue available. Results showed that the higher the listeners’ empathy, the more accurate they were matching intonation to meaning. Esteve-Gilbert et al. (2020) concluded that listeners use empathy as a pragmatic ability to process linguistic information and that empathy influences how listeners use intonation to infer pragmatic meaning, especially when linguistic information is ambiguous or non literal. Pragmatic skills like empathy need to be considered when investigating intonation processing in typical and atypical individuals. 
The present study






SCRATCH/IDEAS

Intonation refers to the melody that every language manifests throughout the course of the speech. One of the main components of intonation is pragmatic information, an essential element when disambiguating utterances, especially in second language acquisition. Intonation and pragmatic skills of an individual seems to play an important role in language comprehension (Esteve-Gilbert et al., 2020), but this is a field scarcely studied. We know that with the same linguistic elements native speakers are able to successfully communicate, however, L2 learners struggle to process language input.

From the perspective of the learner, those with a higher level of empathy, are expected to perform a more successful approach to the pragmatic meaning, in other words, these learners with better pragmatic skills are capable to better resolve intonational cues from the utterance. In research from Esteve-Gibert et al. (2020), they found that individual empathy influences have an effect regarding the intonation – meaning binomial association. Thus, less empathic individuals were not able to extract meaning or disambiguate an ambiguous referent on the basis of utterance they perceived. However, those learners more empathic and more pragmatically skilled were able to construct different meaning associations based on the intonation cues they were given.

The purpose of this project is to study the perception and processing of prosody in second language acquisition. 





 
DEFINITION OF EMPATHY: Empathy can be defined as the capacity to discern another person’s communicative intent. Therefore, empathy can serve as an aiding factor in the development of pragmatic skills.


Generally, research on L2 intonation has been primarily concerned with production, with L1 transfer being accounted as an important factor. In his dissertation, Trimble (2013a?) looked at L2 Spanish learners' production of intonational patterns for broad focus declaratives and absolute interrogatives after a semester-long study abroad. 
Trimble (2013b?) examined the perception of intonational cues by L2 learners of Spanish and he found that intonational cues that were absent form participants’ L1 were difficult to perceive. Furthermore, his study points towards a development of the L2 intonation system, modulated by proficiency and time spent studying abroad. 


Possible intro? 

It is widely acknowledged that intonation is an essential element for communication and a key element of language grammar. Prosody, intonation and melodic aspects of speech is one aspect that affects individuals differently. Intonation has a semantic function, and through the adequate cognitive decoding of intonation a speaker can signal sentences, such as declarative or interrogative. Additionally, a speaker can signal pragmatic functions, because it can be used to express a wide range of connotations, such as when a speaker presents a polite discourse (Astruc, Vanrell, & Prieto, 2016), bias and presupposition (Henriksen, Armstrong, & García-Amaya, 2016). One essential aspect of second language acquisition and language comprehension is that in the presence of the same linguistic elements, listeners can arrive at different interpretations of the message (e.g., Cain, Lemmon, & Oakhill, 2004; Gandour Hambrick, & Ferreira, 2007). The difficulty in interpreting, and decoding the multiple functionalities of intonational contours makes the L2 learning a challenge. 


