## Comments to the Author

\RC{The study analyses the influence of empathy in the perception and processing of intonation in questions and statements in L2 Spanish and shows that higher empathic individuals, in comparison with lower empathic individuals, appear to be more sensitive to intonation cues. In my opinion, the quality of the paper is very good and the conclusions make it a highly citable one and not only for the case of Spanish L2 but in general. 

Below you can find a by-section review and some comments.

The goals and hypothesis of the paper are clear and well-defined.

}

We thank the reviewer for taking the time to read our manuscript and for the painstaking effort they have put in in examining our stimuli. 
The revised version of our paper is without a doubt much stronger after taking their feedback into consideration. 

\Done




\RC{As for the state of the art, page 29, line 6 states: "the current body of research is limited to studies on pronunciation accuracy." And I think that is not accurate, there are studies that include empathy as an important factor for intonation perception (in L1 and mostly from psychology that is true) [LINK].

And, then, specifically for Spanish L2, a recent poster presented in New Sounds 2022 uses the Autism Spectrum Quotient (I don't know if they publish abstracts as short papers) [LINK].

Maybe you can add this info in the introduction stating that it is a very recent and promising field of research and that it helps us to understand individual variation and that way you won't need to change much in your text.
}

We thank the reviewer for providing us with these references. 
We have taken their advice and included both of them in the introduction, along with their characterization of this field of research (as a side note, we actually saw the poster the reviewer recommends at New Sounds and were able to chat with the author!). 
We do, however, wish to point out that the sentence the reviewer quotes (p. 29, line 6) refers to the body of research on empathy in SLA, not monolinguals [i.e., @aziz2010common], nor the Autism Spectrum Quotient [i.e., @shang2022ns]. 
Regardless, the aforementioned references are welcomed additions to the manuscript.

\Done
\Easy





\RC{The methodology of the paper is outstanding, a great sample size (225 listeners), good materials (with several Spanish varieties included) and a state-of-the-art statistical analysis for fussy reviewers and an innovative one (at least for our discipline), that I don’t fully understand, so maybe it is a good idea to organize a workshop on that in a future congress.}

We again thank the reviewer for their kind words. 
We already have plans to conduct a workshop on Drift Diffusion modeling in the (semi) near future. 

\Done
\Easy




\RC{I have only have questions regarding those "64 critical items" that (I think) can be easily solved including examples or a description of the patterns the speakers used or better (and you will see why in the comments) how you elicited the data and saying something like "variation is wonderful, students must be exposed to a wide range of intonational patterns and we are not interested in their pragmatic meaning for this study".}

We agree with the sentiment expressed here by the reviewer, though our characterization of our interest in pragmatic meaning is slightly different. 
As noted by the reviewer, our stimuli contain a wide range of intonational patterns, both between Spanish varieties and within individual Spanish speakers. 
We see this as a strong point of our study, and this is indeed by design. 
Importantly, this restricts us in what we can say about *how* and *why* specific utterance types are more or less difficult. 
Our explanation is that in this first step we are more focused (in this article) on the learners' ability to extract pragmatic meaning generally. 
In other words, whether a given utterance is a question or a statement, and not specifically, as in their ability to extract different pragmatic meanings within a specific type of question. 
Other work, such as that being conducted by Shang [e.g., @shang2022ns] is already focusing on the role of individual differences and how they relate to the relative difficulties of specific tunes. 
We see this as the next step in our research on empathy. 

\Done
\Easy




\RC{First, silly question, why do the listeners need intonation in wh- questions? They have the marker "qué, quién, cómo"... That is all they need, so I don't understand why this type of question is included in the study.}

In theory this is true, though these same lexical items can also be present in statements (or parts of statements), e.g., "Cuando empieza el partido...", "Cuando empiece el partido...", "¿Cuándo empieza el partido?". 
Initially, we had the same concern with the stimuli, which are the exact stimuli used in @bustin_2020. 
In other words, we feared that the task would be too easy for learners. 
However, the results from our study, as well as those of @bustin_2020, in both accuracy and reaction time, make it clear that, regardless of the presence of the wh- word, the task is still difficult for learners. 

\Done
\Easy




\RC{I know that the stimuli are in the supplementary materials, but I miss something in the text either an example (or two of them) or making explicit of the type of stress that you have included and why. The reason is that a lot of foreign speakers (that is the case for example for Dutch, Japanese and Chinese if I remember it correctly) find more difficult to distinguish between statements and questions when the last word of the sentence is stressed in the last syllable (aguda). And that has two main reasons, 1) compression and truncation of the tonal movements and 2) (and of special importance given the varieties included among your stimuli) most of Mexican, Peninsular Spanish, Chilean, Peruvian statements can be slightly rising. In pragmatic descriptions such as Prieto \& Roseano (2010) that final contour is characterised as "statement of the obvious" but, in fact, that is the pattern that we find most of the times that we elicit statements that have the slightest hint of common ground information, for example, in narratives. Moreover, in some varieties of Mexico and Chile, slightly rising (L* !H\%) is the standard neutral pattern. This has a direct implication in the perception of questions by native speakers that counterintuitively, need a higher F0 rise in order to say that something is a question than foreigners that speak usually speak languages where there are not rising statements (I would give you references but they are mine, so maybe when the paper is published, we can talk in a congress). Maybe you don't find that because English-speaking speakers are used to uptalk?}

These are great insights. 
We agree that a few clear examples are necessary. 
We have provided this information in the method section of the revised manuscript. 

\Done
\Easy




\RC{Before I start criticizing your stimuli in the follow paragraphs, I want you to know that I very much appreciate that you made them public and that if every researcher did this we will find problems in every dataset. So, this does not diminish your work at all. Now, some of the things that I am going to say are not solvable in a reviewed version and I am aware of that, and I do not expect you to solve them, the paper is publishable as long as you include the sentence that I said before saying that the sentences have several contours and several pragmatic meanings.}

We appreciate the reviewers honesty and willingness to take the time to examine our materials. 
We believe this makes our paper stronger and promoting open science only pushes the field forward. 

\Done
\Easy




\RC{Firstly, eliciting real broad-focus sentences is not easy and not only because the tendency to the statement of the obvious, for example, your andalusian\_match\_declarative-broad-focus\_David-leia-el-libro has a slightly (but audible and present in the pitch contour) narrow-focus intonation (rising stressed syllable) and the only narrow-focus that I could find among all your stimuli. So, maybe we are calling narrow-focus to different things, let me know if we are.}

Our elicitation of narrow focus is indeed slightly different from what is generally found in the literature and this is clear when comparing our narrow focus utterances with most of the documented tunes in the extant literature. 
Most investigations do this XXX
We did this XXX
We have made sure to explain how we elicited the utterances from our speakers in the revised manuscript and provide additional detail in the supplementary materials. 

\WorkInProgress
\Easy




\RC{As for the wh- questions, Spanish has loads of patterns, for example in Argentina wh- questions can be rising or falling depending on politeness, in Peninsular Spanish are usually falling but they can be rising, and usually is the same for any dialect. And, then we have all the biased intonation patterns, for example, your Andalusian speaker is using the "surprised one" L+H\*L\%, which happens to coincide with the pattern for focus, in all the wh- questions except in "andalusian\_match\_interrogative-partial-wh\_Por-que-ama-la-navidad", where she uses the L\*H\%, the prototypical one for yes-no questions in standard Castilian Spanish.

For the rest, most of your speakers have chosen rising patterns for their wh-questions but that is not the most frequent pattern.
}

\WorkInProgress
\Easy




\RC{As for focus, all your speakers should be doing a rising stressed syllable and falling ending (L+H\* L\%), that is pretty much panhispanic and crosslinguistically really frequent. But they are not, the case of the Peruvian speaker is salient because is using a monotonous tone, just the opposite of what she should be doing.}

\WorkInProgress
\Easy




\RC{In the case of the Argentinian speaker if you look at the sentences side by side you will see that in the supposedly narrow sentence the peak is a bit earlier but it is still in the post-stressed syllable. We will expect here the Argentinian narrow-focus pattern, which is the most recognizable thing of their accent and the only case in which Spanish has a tritonal accent L+H\*+L (peak in the middle of the stressed syllable surrounded by low tones).}

\WorkInProgress
\Easy




\RC{And then your Andalusian speaker has been innovative and has chosen for most of the cases the statement of the obvious pattern (realised as L\*H\%) therefore using the y-n question pattern. The context that Prieto and Roseano (2010) have for that is:
A: ¿De quién es el hijo?
B: ¡De quién va a ser! de Guillermo
So for your data would be something like: A: María bebe el vino. (while she is thinking: obvio, ¿por qué me lo preguntas?)
}

\WorkInProgress
\Easy




\RC{In the rest of them I think that she is trying to put the focus on the verb, but the result is really strange. To do that, you would need something like “Mariano HAbla | del tiempo (and does not another thing)” and you will have a small pause with compressed post-focal material etc. What she does is just weird.}

\WorkInProgress
\Easy




\RC{And lastly, yes-no questions, in general rising (here the Andalusian speaker is using the Madrid standard Spanish), but falling in Cuba, Puerto Rico, all the Caribbean, North of Spain, Canary Islands... The good thing is that the falling patterns that you have are not easily mistaken with a statement (for example questions of Medellín (Colombia) are) and the bad thing again is that you have more than one pattern.}

\WorkInProgress
\Easy




\RC{Ok, so the message after this is that the choice of a pattern by the speakers has made that some of the stimuli are more difficult that others and that maybe you could solve that by adding a new variable "pattern used", which for most of the cases will be the interaction between variety and utterance type but for those speakers that use different patterns it won't. In fact, if you redo the analysis in order to see the effect of the contour, I would use this variable instead of utterance type because most of the supposedly narrow-focus sentences are broad-focus and will share the L\*L\% contour. And again, I am not saying that you do that for the current paper, you can prepare a new experiment to focus on intonational patterns.}

\WorkInProgress
\Easy




\RC{Results. Nothing to say, beautifully solved, I loved the inclusion of speech rate as a variable that could affect the results. 

Congratulations on your work and I hope to see the reviewed version soon.
}

\WorkInProgress
\Easy
