---
title: "Open Science Pre-Registration for Empathy project"
output: github_document
---


# Registration Metadata

**Title**: Production, perception, and processing of prosody in second language accquisition

**Description**: Specifically, we look at the role of empathy in the development of L2 prosody by analyzing the perception of intonation in questions and statements in L2 Spanish.

**Contributors**: *to be added via osf.io*

**Category**: Project

**Affiliated institutions**: 

**License**: TBD

**Subjects**: Social and Behavioral Sciences

**Tags**: 






# Study Information

<!--
Isabelle and Kim: this is some cut and paste mashup from the IRB. 
Feel free to take whatever you want from here and use it for a 3/4 paragraph background/motivation type description of the project. (you can literally use any of it word for word, if you want, but you have free reign). Also see https://osf.io/qvjzy for an example of what this description should look like more or less. 

The purpose of this project is to study the production, perception, and processing of prosody in second language acquisition. 
This research looks at the role of individual pragmatic skills in the process of learning a new language. 
Specifically, we look at the role of empathy in the development of L2 prosody by analyzing the perception of intonation in questions and statements in L2 Spanish.

The objectives of this research are twofold. 
First, the project intends contribute to cumulative science by replicating the Brandl et al. (2020) finding demonstrating that perception and processing of L2 intonation improves in conjunction with L2 proficiency and as a function of intonation type. 
Second, this research will extend the current findings on perceptual development to include pragmatic skills, specifically empathy. 

The purpose of this project is to study the production, perception, and processing of prosody in second language acquisition. 
This research looks at the role of individual pragmatic skills in the process of learning a new language. 
Specifically, we look at the role of empathy in the development of L2 prosody by analyzing the perception of intonation in questions and statements in L2 Spanish.
L2 learners gradually acquire Spanish prosody as they gain proficiency in the language. 
The extant literature shows that 'yes/no'-type questions harder to process and acquire, when compared with simple statements (Brandl et al., 2020). 
Recent research has also shown that empathy influences language processing in how listeners interpret intonation and meaning when words are ambiguous (Esteve-Gilbert et al., 2020). 
Specifically, higher empathy individuals, in comparison with lower empathy individuals, appear to be more sensitive to intonation cues in the process of forming sound-meaning associations. 
In short, individuals with more pragmatic skill (higher empathy) are able to use intonation to resolve temporary lexical ambiguity that can lead to confirmatory vs. contrasting interpretations. 
This research underscores the importance of considering individual pragmatic differences when examining intonational meaning processing and sentence comprehension. 
Thus, we extend this research to second language acquisition in order to determine if individual differences in pragmatic skill affect the development of intonation in L2 processing and sentence comprehension.
--> 


Using existing data from Brandl, Gonzalez and Bustin- Development of intonation in L2 Spanish
Have stimuli from Brandl study <!-- Clarify that we're re-recording the sentences and its not the exact same speakers they they used but the same items -->
Using data from empathy influences how listeners interpret intonation by D'Imperio et al


### Hypotheses

H1. L2 learners of Spanish with a higher empathy quotient have a higher sensitivity to intonation in 
Spanish phrases than L2 learners of Spanish with a lower empathy quotient.

H2: L2 learners of Spanish and Spanish monolinguals with a higher level of proficiency in Spanish are more sensitive to intonation differences in Spanish statements and questions. 

<!-- 
Draft but something to this effect: 

Research question 1: Is perceptional development in L2 Spanish modulated by proficiency and intonation type (i.e., Brandl et al., 2020). 
Hypothesis: Accuracy will increase and processing time will decrease as a function of proficiency and intonation type. Yes-no questions will present the most difficulty for L2 learners of Spanish.

Research question 2: Do pragmatic skills modulate rate of development in L2 prosody?
Hypothesis: Based on the findings of Esteve-Gilbert et al. (2020), we posit that prosodic development will occur sooner and at a faster rate in higher empathy individuals.

--> 





# Design Plan

### Study type

Observational Study - Data is collected from study subjects that are not randomly assigned to a treatment. 
This includes surveys, “natural experiments,” and regression discontinuity designs.

### Blinding

No blinding is involved in this study.

### Is there any additional blinding in this study?

There is no additional blinding in this study.
 
### Study design

<!--
Describe your study design. The key is to be as detailed as is necessary given the specific parameters of the design. There may be some overlap between this question and the following questions. That is OK, as long as sufficient detail is given in one of the areas to provide all of the requested information. Examples include two-group, factorial, randomized block, and repeated measures. Is it a between (unpaired), within-subject (paired), or mixed design? Describe any counterbalancing required.
-->

Participants take the empathy quotient assessment <!-- Should we explain this further? Describe the task, how they'll complete it, etc. -->
Participants take a Spanish proficiency assessment, the lextale. It is a measure of vocabulary knowledge that we're using as a proxy for proficiency.

Assessment will ask participants to recognize on-screen text as “a word” or “not a word” 
Participants will distinguish between matched and mismatched auditory and visual stimuli
Auditory stimuli: pre-recorded sentences adapted from Brandl et. al study
Visual stimuli: sentences adapted from Brandl et. al study
Fillers: the "mismatched" ones (i.e. sentences that, at surface level, could be either declarative or interrogative)
     e.g. “¿Cuándo llegaron a Málaga?” vs. “Cuando llegaron a Málaga.”
Participants will be asked to identify a match or mismatch between each set of auditory and visual stimuli
Auditory and visual stimuli will/ will not (not sure which one it is) be presented simultaneously

### Randomization

Target items for all tasks (2AFC, LexTALE, Empathy quotient) are presented randomly via PsychoPy. 
In the case of the 2AFC task, target items (auditory stimuli) are drawn randomly from 8 distinct varieties of Spanish. 
No other randomization is necessary.







# Sampling Plan 

### Existing Data

Registration prior to creation of data

### Explanation of existing data

NA

### Data collection procedures*

We will recruit XXX human participants for this study. 
Participants will be native English speakers L2 learners of Spanish with varying levels of proficiency.
Participants will be recruited via ProlificAC and will be compensated at a rate of XXX for their time.

### Sample size*

All participants will be native speakers of American English who range from functionally monolingual to highly proficient in Spanish (bilinguals). 
All participants with knowledge of Spanish will be second language learners, operationally defined as having begun the endeavor of learning Spanish after the age of 13.

### Sample size rationale

Following Brandl et al. (2020), we assume the effect size for perceptual learning to be moderate in terms of the criteria set forth for L2 research by Plonsky et al. (2015?) (D = 0.6). 
Based on this assumption, we estimate that we will need XXX participants to have and 80% chance of capturing the effect with a type II error rate of 5%. 
Our hypotheses related to empathy as a possible mediator of perceptual learning is exploratory and thus we do not base our sample size estimate on any parameter estimates related to this effect. 

###  Stopping rule

We will stop data collection once XXX participants have completed all tasks or time runs out.




# Variables 

### Manipulated variables

Our experiment will manipulate a 'condition' variable that refers to the sentence type. 
Specifically, we will present auditory stimuli that include declarative (broad focus, narrow focus) and interrogative (yes-no/polar/total, wh-/non-polar/partial) sentences. 
The sentence stimuli are audio recordings spoken by native Spanish speakers of different varieties. 

### Measured variables*

For the 2AFC task there are two measured variables: response and response time. 
The first outcome variable is participants' responses to the auditory stimuli, i.e., if they respond 'X' or 'Y'. 
The measured variable is categorical and will be coded as 0 for 'X' responses and 1 for 'Y' responses.
Th second outcome variable is participants' response time, that is, the time in ms a participant takes to make a response. 

Our experiment will measure vocabulary size via the LexTALE task, which will be used as a proxy for language proficiency and entered into our analysis as a continuous predictor.
Finally, we will include measure of the construct *empathy* based on the Empathy Quotient (CITE). 
The empathy score for each participant will also be entered into our analysis as a continuous predictor.

### Indices

NA




# Analysis Plan 

### Statistical models*

We utilize Bayesian data analysis for statistical inferences. 
For the response data we will fit a hierarchical logistic regression model in which the response ('X', 'Y') is fit as a function of *condition* (broad focus, narrow focus, yes-no question, wh-question), *empathy* (empathy quotient score), and *proficiency* (LexTALE score). 
The random effects structure will include by-participant random intercepts with random slopes for condition, as well as random intercepts for items and speaker variety, i.e., `response ~ condition * empathy * proficiency + (1 + condition | id) + (1 | item) + (1 | speaker_variety)`. 
The model will use regularizing, weakly informative priors. 

### Transformations

The proficiency and empathy predictors will be standardized to have a mean of 0 and scale 1.
The *condition* predictor will be dummy coded with wh-questions set as the reference level. 

### Inference criteria

We will sample the posterior distribution of the model for statistical inferences. 
A region of practical equivalence (ROPE) will be established around a point null value of 0 (Kruschke, 2018) using the following formula:

$$\frac{\mu_1 - \mu_2}{\sqrt{\frac{\sigma_1^2 + \sigma_2^2}{2}}}$$ 

For all models, median posterior point estimates are reported for each parameter of interest, along with the 95% highest density interval (HDI), the percent of the region of the HDI contained within the ROPE, and the maximum probability of effect (MPE).
For statistical inferences, a posterior distribution for a parameter &beta; in which 95% of the HDI falls outside the ROPE and a high MPE (i.e., values close to 1) were taken as
compelling evidence for a given effect.
The analyses will be conducted in R and models fit using `stan` via the R package `brms` (Bürkner, 2018). 

### Data exclusion

We will exclude data according to the following criteria:

- Error during data collection
- Clear lack of understanding or engagement during the task, i.e., all 1 responses.

### Missing data

Our models are robust to missing data, thus no specific measures will be taken to account for this possibility.

### Exploratory analysis

Given that the construct *empathy* is particularly understudied in SLA research, our analysis of this construct is exploratory in nature. 
Based on D'Imperio et al. (CITE), we posit that learners with higher empathy levels may be more attuned to intonational variability. 
Specifically, we hypothesize that the effect of empathy on perceptual learning will be additive, 
thus higher empathy learners may perform better on the 2AFC task at lower levels of proficiency. 

# Other

NA


# References

Brandl, A., González, C., & Bustin, A. (2020). The development of intonation in l2 spanish: A perceptual study. In A. Morales-Front, M. J. Ferreira, R. P. Leow, & C. Sanz (Eds.), Hispanic linguistics: Current issues and new directions (pp. 12–31). John Benjamins Publishing Company.

Baron-Cohen, S., & Wheelwright, S. (2004). The empathy quotient: An investigation of adults with asperger syndrome or high functioning autism, and normal sex differences. Journal of Autism and Developmental Disorders, 34(2), 163–175.
